Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,7 +19,10 @@ runs:
         sudo snap install --edge edgexfoundry
         sudo snap install --edge ${{inputs.edgex_device_snap}}
         sudo snap start ${{inputs.edgex_device_snap}}.${{inputs.edgex_service_name}}
-        echo "::error file=app.js,line=10,col=15::Something went wrong"
-        exit 1
-        curl http://localhost:48082/api/v1/device/name/${{inputs.edgex_device_name}}
+        if curl -s http://localhost:48082/api/v1/device/name/${{inputs.edgex_device_name}} | grep -q "${{inputs.edgex_device_name}}A"; then
+          echo ok
+        else
+          echo "::error ::Did not respond"
+          exit 1
+        fi
       shell: bash
